name: .NET Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      # You may pin to the exact commit or the version.
      # uses: PaulHatch/semantic-version@3d2ea28b25c9a892b07cd24b5675300b701fcef5
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        # Set to specify a specific branch, default is the current HEAD
        #branch: # default is HEAD
        # The prefix to use to identify tags
        tag_prefix: '' # optional, default is v
        # A string which, if present in a git commit, indicates that a change represents a major (breaking) change. Wrap with '/' to match using a regular expression.
        #major_pattern: # default is (MAJOR)
        # A string which, if present in a git commit, indicates that a change represents a minor (feature) change. Wrap with '/' to match using a regular expression.
        #minor_pattern: # default is (MINOR)
        # Pattern to use when formatting output version
        #format: # default is ${major}.${minor}.${patch}
        # Path to check for changes. If any changes are detected in the path the 'changed' output will true. Enter multiple paths separated by spaces.
        #change_path: # optional
        # Use to create a named sub-version. This value will be appended to tags created for this version.
        #namespace: # optional
        # If false, only full versions, i.e. 'v1.0.0', will be supported as tags. If true, tags will support truncated minor and patch versions such as 'v1' (default).
        #short_tags: # default is true
        # If true, every commit will be treated as a bump to the version.
        bump_each_commit: true # default is false
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Coverlet coverage test
      # You may pin to the exact commit or the version.
      # uses: b3b00/coverlet-action@a53722e8b9e901f31e2f639df74cb0c5bd15a12e
      uses: b3b00/coverlet-action@1.1.7
      with:
        testProject: 'Cowsay.UnitTests/Cowsay.UnitTests.csproj'
        output: 'lcov.info'
        outputFormat: 'lcov'
        threshold: 100
    - name: Coveralls GitHub Action
      # You may pin to the exact commit or the version.
      # uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057
      uses: coverallsapp/github-action@1.1.3
      with:
        # 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Path to lcov file
        path-to-lcov: ./Cowsay.UnitTests/lcov.info # default is ./coverage/lcov.info
        # Job flag name, e.g. "Unit", "Functional", or "Integration". Will be shown in the Coveralls UI.
        flag-name: Unit # optional
        # Set to true if you are running parallel jobs, then use "parallel_finished: true" for the last action.
        #parallel: # optional
        # Set to true for the last action when using "parallel: true".
        #parallel-finished: # optional
        # Coveralls Enterprise server (more info: https://enterprise.coveralls.io)
        #coveralls-endpoint: # optional, default is https://coveralls.io
        # The root folder of the project that originally ran the tests
        #base-path: # optional
        # Override the branch name
        #git-branch: # optional
        # Override the commit sha
        #git-commit: # optional
