name: Release build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${{ github.event.release.tag_name }} /p:AssemblyVersion=${{ github.event.release.tag_name }}
    - name: Pack all packages with version
      run: |
        dotnet pack --configuration Release --no-build /p:Version=${{ github.event.release.tag_name }}
    - name: Push library packages to nuget.org
      run: |
        dotnet nuget push ./src/Cowsay/bin/Release/Cowsay.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push ./src/Cowsay.Abstractions/bin/Release/Cowsay.Abstractions.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push ./src/Cowsay.Extensions.DependencyInjection/bin/Release/Cowsay.Extensions.DependencyInjection.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
    - name: Push CLI tool to nuget.org
      run: |
        dotnet nuget push ./src/Cowsay.CLI/nupkg/Cowsay.CLI.${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json


