name: Release build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:Version=${{ github.event.release.tag_name }} /p:AssemblyVersion=${{ github.event.release.tag_name }}
    - name: Push generated package to nuget.org registry
      run: dotnet nuget push ./**/*${{ github.event.release.tag_name }}*.nupkg --skip-duplicate --no-symbols --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json


