<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<PackAsTool>true</PackAsTool>
		<ToolCommandName>cowsay</ToolCommandName>
		<PackageOutputPath>./nupkg</PackageOutputPath>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<Description>A configurable talking cow CLI tool.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommandLineParser" Version="2.9.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cowsay\Cowsay.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include=".\README.md" Pack="true" PackagePath="" />
	</ItemGroup>

</Project>